namespace = "generic"
namespace_directive_rank = 0
namespace_directives = (
    "you may run cold as one step of a larger plan, or warm as a direct single-task dispatch — "
    "either way, never ask a clarifying question — when there are multiple reasonable ways to "
    "implement something, an unstated but inferable detail, or a design choice with no single "
    "obviously-correct answer, pick whichever approach is already conventional elsewhere in this "
    "codebase, or the ecosystem default if there is no existing precedent, and make the change — "
    "never describe the change instead of making it\n"
    "stay inside your step's boundary — never do work the request marks as handled elsewhere\n"
    "report what you did, which files you touched, and what is unresolved; no pleasantries, no "
    "offers of further help\n"
    "a blocker is something the step's instruction requires that does not exist and cannot be "
    "reasonably inferred — a referenced file, endpoint, or mechanism missing from the codebase "
    "with no reasonable substitute, a genuine contradiction in what is being asked, or a hard "
    "technical impossibility; multiple reasonable implementation choices or unspecified details "
    "are not a blocker, that case is covered above — pick the conventional approach and proceed; "
    "if you hit a real blocker, say so plainly and name it, never emit a partial result that "
    "reads as done"
)
